language: node_js
node_js:
    - 4.1.2
sudo: false
cache:
    directories:
        - node_modules
addons:
    code_climate:
        repo_token:
            secure: "xE26BkvFxs9Jztx2ZA4K06xzft+2E985Mv5uiyOvENk9swZXwiOtuw0MK311hteMZZOmkKO1TiwJ3PnMkra2K1p3pFBjkJoa4sCSuJN8qdyhyA0A9cwS3bec0fJJLydA5MHi1QVF29g6Y2ubBsfyifSxXiG24lDmYG2OCVEUddj0EtfQG5+zshaRCfJR5SC/UxoxDPxeb4FL1Kg7gDQRvQMabrxGhqU5LxwVhjBkGGgqAIryWugApOkuPLp+7kAvxHVdrId4w5salSg21OjfrHVGOCRMyUnkwnxxnF/yEPySVhL1idSUjDsS6rtZSK5gdc67N9EC14YfgXndeatEsfWa2nuiS5M0gJjZS/YOAiv4MrghDBDxBDLPaCv+R3Fx0VdY6S+zOl9jCZEnYIHvpSmm77n90aib494k7IRAH3m9UEujVkJ8XIz5BdNAOOKsDJU8TLktsGq973rqXc+dgPOBTCtdSsXgBLYC9jnyKUC3h2omwCjHgPCUzBvrYAgc9hmkuQhu0gLlifxYAvgsEHLikF3X3z18fDFdyj3A473sRwNxID9Kjflslg2qZ4kcLyGbvNYrsNylZNjDzHXyfSGcLyG5nMnviJG4rzjlVJgDQCTupDKMQLbbfJXcTT75hHX0/yyan4ex/jf1XG0h2aE/ZJP1s2TBYTT5b4rFHfY="
after_script:
    - npm install codeclimate-test-reporter
    - gulp coverage
    - codeclimate-test-reporter < coverage/lcov.info